export const projects = [
    {
        name: 'Mon-portfolio',
        description: "Bon comme le dis le titre du dépôt repository, c'est mon portfolio professionnel.",
        githubLink: 'https://github.com/Sakab2003/Mon-portfolio',
        projectLink: 'https://github.com/Sakab2003/Mon-portfolio',
        tech: ['JavaScript', 'Next.js'],
        photo: ['/images/Project1_1.jpg', '/images/Project1_2.jpg', '/images/Project1_3.jpg'], 
    },
    {
        name: 'Salon_web',
        description: "En parralele qvec l'application mobile salon mobile, on a une plateforme web qui sert de saas pour les admin pour la gestion ainsi que le suivie des clients par les manageurs des salons.",
        githubLink: 'https://github.com/Sakab2003/Salon_web',
        projectLink: 'https://github.com/Sakab2003/Salon_web',
        tech: ['PHP'],
        photo: ['/images/Project2_1.jpg', '/images/Project2_2.jpg', '/images/Project2_3.jpg'],
    },
    {
        name: 'Salon_mobile',
        description: 'Pojet a Kuilinga technologies',
        githubLink: 'https://github.com/Sakab2003/Salon_mobile',
        projectLink: 'https://github.com/Sakab2003/Salon_mobile',
        tech: ['Dart', 'Flutter'],
        photo: ['/images/Project3_1.jpg', '/images/Project3_2.jpg', '/images/Project3_3.jpg'],
    },
    {
        name: 'Expert-de-la-semaine',
        description: 'Choix des personnes qui vont par la suite consecutivement se passer la main pour passer comme expert de la semaine pour nous presenter un projet de son choix.',
        githubLink: 'https://github.com/Sakab2003/Expert-de-la-semaine',
        projectLink: 'https://github.com/Sakab2003/Expert-de-la-semaine',
        tech: ['PHP'],
        photo: ['/images/blog.jpg'],
    },
    {
        name: 'raproser',
        description: 'Modification du projet raproser de kuilinga technologies fait le 13 juillet 2026.',
        githubLink: 'https://github.com/Sakab2003/raproser',
        projectLink: 'https://github.com/Sakab2003/raproser',
        tech: ['Blade', 'Laravel'],
        photo: ['/images/blog.jpg'],
    },
    {
        name: 'Projet-de-l-universit-virtuelle.',
        description: 'Projet universitaire virtuel mis en place pour la gestion.',
        githubLink: 'https://github.com/Sakab2003/Projet-de-l-universit-virtuelle.',
        projectLink: 'https://github.com/Sakab2003/Projet-de-l-universit-virtuelle.',
        tech: ['PHP', 'MySQL'],
        photo: ['/images/blog.jpg'],
    },
    {
        name: 'focus-',
        description: "Premier projet mis en ligne par moi même. Dans le but d'avoir le lien de mon application.",
        githubLink: 'https://github.com/Sakab2003/focus-',
        projectLink: 'https://github.com/Sakab2003/focus-',
        tech: ['Blade', 'Laravel'],
        photo: ['/images/blog.jpg'],
    },
]